name: Jeyser site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: yarn install
      - run: bin/retrieve-documentation
      - run: yarn lint
      - run: yarn gatsby build
